inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: false
  DefaultFormatter: clang
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Encoding:
  Enabled: true
